FROM python:3.14-slim

WORKDIR /workspace

# Upgrade pip
RUN pip install --upgrade pip

# Install pipenv
RUN pip install pipenv

# Install deps
COPY app/Pipfile app/Pipfile.lock ./app/
WORKDIR /workspace/app
RUN pipenv install --dev --system

# Copy shared libraries
COPY shared_libs/ ../shared_libs/

# Copy application files
COPY app/ .

CMD ["python", "-m", "pytest", "test_app.py", "test_database.py", "-v", "--cov=.", "--cov-report=term-missing"]