FROM python:3.14-slim

WORKDIR /app

# Upgrade pip
RUN pip install --upgrade pip

# Install pipenv
RUN pip install pipenv

# Install deps
COPY Pipfile Pipfile.lock ./
RUN pipenv install --dev --system

COPY . .

CMD ["python", "-m", "pytest", "test_app.py", "test_database.py", "-v", "--cov=.", "--cov-report=term-missing"]