project_id            = "cc6-api"
firebase_site_suffix  = "-prod"
region                = "us-east1"
domain_monolithic_app = "app.cc6.co.uk"
domain_api            = "api.running.cafe"
domain_admin          = "admin.running.cafe"
domain_frontend       = "app.cc6.co.uk"
cors_origins          = "https://app.cc6.co.uk,https://app.rr10.org.uk"
