project_id          = "running-cafe-staging"
firebase_project_id = "running-cafe-staging-b7491"
region              = "us-east1"
domain_api          = "api-staging.running.cafe"
domain_admin        = "admin-staging.running.cafe"
domain_frontend     = "app-staging.cc6.co.uk"
