project_id      = "running-cafe-staging"
region          = "us-east1"
domain_api      = "api-staging.running.cafe"
domain_admin    = "admin-staging.running.cafe"
domain_frontend = "app-staging.cc6.co.uk"
