project_id           = "running-cafe-staging"
firebase_site_suffix = "-staging"
region               = "us-east1"
domain_api           = "api-staging.running.cafe"
domain_admin         = "admin-staging.running.cafe"
domain_frontend      = "app-staging.cc6.co.uk"
