FROM python:3.14-slim

WORKDIR /workspace/admin

# Upgrade pip
RUN pip install --upgrade pip

# Install pipenv
RUN pip install pipenv

# Install deps
COPY admin/Pipfile admin/Pipfile.lock ./
RUN pipenv install --dev --system

# Copy shared libraries
COPY shared_libs/ ../shared_libs/

# Copy application files
COPY admin/ .

CMD ["python", "-m", "pytest", "test_admin.py", "-v", "--cov=.", "--cov-report=term-missing"]