FROM python:3.14-slim

WORKDIR /workspace/api

# Upgrade pip
RUN pip install --upgrade pip

# Install pipenv
RUN pip install pipenv

# Install deps
COPY api/Pipfile api/Pipfile.lock ./
RUN pipenv install --dev --system

# Copy shared libraries
COPY shared_libs/ ../shared_libs/

# Copy application files
COPY api/ .

CMD ["python", "-m", "pytest", "test_api.py", "-v", "--cov=.", "--cov-report=term-missing"]